services:
  php: 
    image: tugboatqa/php:7.4-apache

    default: true

    commands:
      init:
        - cp .env.example .env
        - composer install
        - php artisan key:generate
        - ln -snf "${TUGBOAT_ROOT}/public" "${DOCROOT}"
        - chown -R www-data storage bootstrap/cache
        - chmod -R 744 storage bootstrap/cache

  mysql:
    image: tugboatqa/mysql
