services:
  php: 
    image: tugboatqa/php:7.4-apache

    default: true

    # depends: mysql

    commands:
      init:
        - cp .env.example .env
        - composer install
        - php artisan key:generate
        - ln -snf "${TUGBOAT_ROOT}/public" "${DOCROOT}"

  mysql:
    image: tugboatqa/mysql